spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: qa
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8000

resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
