spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: qa
server:
  port: 8100
eureka:
  client:
    eureka-server-port: 8761
