spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: qa
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
